# Generated by Django 5.2.6 on 2025-09-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
